apiVersion: v1
kind: ServiceAccount
metadata:
  name: volsync-addon-controller
  labels:
    app: volsync-addon-controller
    chart: volsync-addon-controller-{{ .Values.hubconfig.hubVersion }}
    release: volsync
    app.kubernetes.io/instance: volsync
    app.kubernetes.io/name: volsync-addon-controller
    component: volsync-addon-controller-serviceaccount