kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:volsync:clusterrolebinding
  labels:
    app: volsync-addon-controller
    chart: volsync-addon-controller-{{ .Values.hubconfig.hubVersion }}
    release: volsync
    app.kubernetes.io/instance: volsync
    app.kubernetes.io/name: volsync-addon-controller
    component: clusterrolebinding
subjects:
- kind: ServiceAccount
  name: volsync-addon-controller
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: open-cluster-management:volsync:clusterrole
  apiGroup: rbac.authorization.k8s.io